export type Theme = {
    id: string;
    name: string;
    mode: "light" | "dark";
    colors: {
        "--background"?: string;
        "--foreground"?: string;
        "--view-1"?: string;
        "--view-2"?: string;
        "--card"?: string;
        "--card-foreground"?: string;
        "--popover"?: string;
        "--popover-foreground"?: string;
        "--primary"?: string;
        "--primary-foreground"?: string;
        "--primary-text"?: string;
        "--secondary"?: string;
        "--secondary-foreground"?: string;
        "--muted"?: string;
        "--muted-foreground"?: string;
        "--accent"?: string;
        "--accent-foreground"?: string;
        "--destructive"?: string;
        "--destructive-foreground"?: string;
        "--disabled"?: string;
        "--border"?: string;
        "--input"?: string;
        "--star"?: string;
        "--ring"?: string;
        "--editor-text-red"?: string;
        "--editor-text-orange"?: string;
        "--editor-text-yellow"?: string;
        "--editor-text-green"?: string;
        "--editor-text-cyan"?: string;
        "--editor-text-blue"?: string;
        "--editor-text-indigo"?: string;
        "--editor-text-purple"?: string;
        "--editor-text-pink"?: string;
        "--editor-highlight-red"?: string;
        "--editor-highlight-orange"?: string;
        "--editor-highlight-yellow"?: string;
        "--editor-highlight-green"?: string;
        "--editor-highlight-cyan"?: string;
        "--editor-highlight-blue"?: string;
        "--editor-highlight-indigo"?: string;
        "--editor-highlight-purple"?: string;
        "--editor-highlight-pink"?: string;
    };
};
export declare function isValidCssColor(color: string): boolean;
export declare function isTheme(maybeTheme: unknown): maybeTheme is Theme;
export declare const cssTextColorVariables: string[];
export declare const csshighlightColorVariables: string[];
export declare function stripAlpha(rgbaHexColor: string): string;
